### ISSUE TITLE
config.atari doesn't exist

### ISSUE THREAD

**Issue by hukz18** [koulanurag/muzero-pytorch#13]
in main.py, there is `if args.case == 'atari':
        from config.atari import muzero_config`,
but there's no atari.py in config folder, just classic_control.py. is this file missing?

**Comment by koulanurag** [comment]
Hi @hukz18 ,

As stated in README, This implementation was just tested on CartPole-v1.  

The line `if args.case == 'atari': from config.atari import muzero_config ` is just a placeholder for others to know where to put their atari config file while could be build based on `classic_control` config.
