### ISSUE TITLE
Probably wrong MCTS implementation

### ISSUE THREAD

**Issue by ChenDRAG** [koulanurag/muzero-pytorch#16]
https://github.com/koulanurag/muzero-pytorch/blob/4c008d06d92ce8cfdfc9b945ce7d1b91dc2af5c2/core/mcts.py#L105
As what I understand, we should reverse search_path and calculate value from bottom to up?

**Comment by ChenDRAG** [comment]
I checked https://github.com/YeWR/EfficientZero 's implementation of MCTS(based on c language), and am almost certain we should reverse search_path.
https://github.com/YeWR/EfficientZero/blob/a0c094818d750237d5aa14263a65a1e1e4f2bbcb/core/ctree/cnode.cpp#L289

**Comment by koulanurag** [comment]
Hi @ChenDRAG, 

Thanks for finding this potential bug. Superficially, it does look that it should be reversed.

I would get back to this in a day or two to investigate its correctness.

Also, I am also happy to accept a PR on it.

**Comment by bAmpT** [comment]
The authors corrected the mistake of not reverseing the search_path in the v2 of the [pseudocode](https://arxiv.org/src/1911.08265v2/anc/pseudocode.py). Another small error is that the target rewards seem to be misaligned, there is a thread on stackoverflow about that: [https://stackoverflow.com/questions/60234530/is-the-reward-value-in-muzeros-pseudocode-misaligned](https://stackoverflow.com/questions/60234530/is-the-reward-value-in-muzeros-pseudocode-misaligned)
